spring.application.name=${APPLICATION_NAME:ebanx-challenge}
server.port=${PORT:8080}

# turn off springdoc api-docs and swagger-ui if you don't want to expose them in production environment
# http://localhost:8080/v3/api-docs
springdoc.api-docs.enabled=true

# http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.enabled=true